### ISSUE TITLE
Blank page after installing on Presta 1.7.0.5

### ISSUE THREAD

**Issue by ilidan85** [ircykk/ship2pay-ps16#3]
Is it even compatible with 1.7 or it only works with 1.6.x?

**Comment by ircykk** [comment]
Hello, only PS 1.6x.
Regards

2017-03-15 9:12 GMT+01:00 ilidan85 <notifications@github.com>:

**Comment by SharakPL** [comment]
FYI Prestashop 1.7 has this functionality built-in. Just go to Payment -> Preferences.
