### ISSUE TITLE
Custom module not Shown after uploading to install

### ISSUE THREAD

**Issue by Yarandi** [ircykk/ship2pay-ps16#5]
Hi , 
when i upload module in module management , the notification say "module download successfully" but i cant see in list to install, 

Prestashop Version is : 1.6.1.17
this issue is not about module status filtering ,
could you help me please?

**Comment by ircykk** [comment]
Hi,
please check if directory name in modules/ is /modules/shiptopay and not
shiptopay-master etc.

2017-11-27 7:37 GMT+01:00 Hamed Yarandi <notifications@github.com>:

**Comment by Yarandi** [comment]
Yes you are right , 
before your answer I had checked the name and fixed it. 
Anyway , Thanks For your response

**Comment by jignaciomartinez** [comment]
I got the same issue but the module isn't in module directory either.

**Comment by fritaasd** [comment]
Same here. No module in directory
