### ISSUE TITLE
Moduł raz działa raz nie.

### ISSUE THREAD

**Issue by Przemko86** [ircykk/ship2pay-ps16#6]
Hej, mam problem z tym modułem na wersji 1.6.1.17. Instaluję, konfiguruję i wszystko jest dobrze do momentu wylogowania się klienta i ponownego zalogowania. Wyskakuje informacja o braku zainstalowanych modułach do płatności. Nadpisywania mam ustawione na NIE. Cache jest wyczyszczony, plik class_index.php jest też usuwany. Co może być przyczyną? Czy moduł wymaga jakiś specjalnych ustawień php?

**Comment by ircykk** [comment]
Nie nic nie wymaga wszystko powinno dziać, jeśli nie działa trzeba już w
kodzie to sprawdzać, nie spotkałem się z takim problemem wcześniej.

W dniu 7 grudnia 2017 09:18 użytkownik Przemko86 <notifications@github.com>
napisał:

**Comment by Przemko86** [comment]
Wydaje się mi, że tutaj jest winny serwer. Na moim działało, a to zwykły współdzielony, na VPS klienta nie chce działać, to jakiś rosyjski serwer, dlatego się pytałem o ustawienia.

Nie wyświetlają się też żadne błędy. Ani debugowanie, ani konsola.

**Comment by Przemko86** [comment]
Wszystko jasne. Doszedłem co powodowało błąd, choć nie mam pojęcia dlaczego. Błąd powodował moduł modułu Zaawansowana zgodność prawna w UE.
